### ISSUE TITLE
Running this example for BookHotel and an invalid city does't show the reason.

### ISSUE THREAD

**Issue by ItIsFelix** [aws-samples/amazon-lex-v2-lambdahook-for-booktripbot#3]
I have 
1. created an example bot in Lex v2.
2. add the Lambda function 
3. Activated the code-hook in BookHotel 
4.  run the Test Bot with the Lambda Funktion. 

Asking for a Hotel with a invalid city like 'Hamburg', doesn't return the message "We currently do not support Hamburg as a valid destination. Can you try a different city?"

**Comment by sita158** [comment]
Hi!
Yes, this code for the Lambda does not build a user friendly error message, it just provides a response to Lex to re-elicit the non-valid slot. You can build upon this code to adapt it to your needs, and provide adequate messages to the end user.
